script:
  hip_notify_doorbell:
    alias: HIP Doorbell Notification
    mode: queued
    sequence:
      - action: notify.mobile_app_robins_iphone
        data:
          title: Doorbell
          message: Someone is at the front door.
          data:
            push:
              sound: default
            image: /local/snapshots/front_door_latest.jpg

automation:
  - alias: HIP Doorbell Notification Handler
    id: hip_doorbell_notification_handler
    mode: single
    trigger:
      - platform: event
        event_type: hip_doorbell_pressed
    condition:
      - condition: state
        entity_id: input_boolean.hip_enabled
        state: "on"
    action:
      - action: script.hip_notify_doorbell
